apiVersion: v1
kind: List
items:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: admin-user
    namespace: kubernetes-dashboard

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: sa-reader
    namespace: default

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: sa-cd-runner
    namespace: default
