apiVersion: v1
kind: List
items:
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: is-manager
  rules:
  - apiGroups: [""]
    resources: ["ConfigMaps", "Secrets", "ClusterRoles", "Roles", "Rolebindings", "ClusterRoleBindings"]
    verbs: ["*"]

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    namespace: default
    name: namespace-admin
  rules:
  - apiGroups: [""]
    resources: ["Pods", "Services", "Deployments", "StatefulSets", "PersistentVolumes"]
    verbs: ["*"]

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    namespace: default
    name: namespace-read-all
  rules:
  - apiGroups: [""]
    resources: ["Pods", "Services", "Deployments", "StatefulSets", "PersistentVolumes"]
    verbs: ["get", "list", "watch"]

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    namespace: default
    name: cd-runner
  rules:
  - apiGroups: [""]
    resources: ["Pods", "Services", "Deployments", "StatefulSets", "PersistentVolumes"]
    verbs: ["get", "list", "watch", "create", "update", "delete",]